-- ===========================================================================
-- Континент страны — ОДНОЙ таблицей, а не правилом, живущим в питоне.
--
-- Владелец: «заполни, разбей всё по континентам, странам, лигам». Замер:
-- `cards.continent` заполнен у 6194 карточек из 25 509 — три четверти колоды
-- сидят в «Прочих», и разбивка по континентам показывает четверть базы.
--
-- ⚠️ ЗАЛИВАТЬ ПО БОЛЬШИНСТВУ ИЗ СВОИХ ЖЕ ДАННЫХ БЫЛО НЕЛЬЗЯ, и я чуть не
-- залил. Проверка перед заливкой показала, что у бразильцев в базе стоят
-- ЧЕТЫРЕ разных континента (africa, europe, north_america, south_america), у
-- испанцев тоже четыре. Причина не в том, что колонка значит что-то другое, а
-- в двойном гражданстве: `country` ставился по ISO из P27, а `continent` — по
-- ИМЕНИ национальности, и у игрока с двумя паспортами они расходятся. Взять
-- большинство значило бы закрепить этот шум как правило.
--
-- Источник правила — `CONTINENT_BY_COUNTRY` в football_scraper/run.py, тот
-- самый, которым континент ставился с самого начала. Здесь он сведён с
-- `COUNTRY_ISO` в пары «код → континент»: 181 код, СПОРОВ НОЛЬ. Правило
-- переехало в SQL целиком, второй копии в питоне не заводится.
--
-- ⚠️ ОКЕАНИИ ЗДЕСЬ НЕТ НАРОЧНО — её нет и в исходном правиле. Новая Зеландия
-- и Австралия остаются в «Прочих», как и были; выдумывать им континент, о
-- котором остальная игра не знает, значит завести шестую кнопку, под которой
-- окажется полтора человека.
-- ===========================================================================
create table if not exists public.country_continent (
  country   text primary key,
  continent text not null
);

alter table public.country_continent enable row level security;
drop policy if exists country_continent_read on public.country_continent;
create policy country_continent_read on public.country_continent for select using (true);
grant select on public.country_continent to anon, authenticated;
grant all    on public.country_continent to service_role;

insert into public.country_continent (country, continent) values
  ('AD','europe'),
  ('AE','asia'),
  ('AF','asia'),
  ('AG','north_america'),
  ('AL','europe'),
  ('AM','europe'),
  ('AO','africa'),
  ('AR','south_america'),
  ('AT','europe'),
  ('AU','asia'),
  ('AW','north_america'),
  ('AZ','europe'),
  ('BA','europe'),
  ('BB','north_america'),
  ('BD','asia'),
  ('BE','europe'),
  ('BF','africa'),
  ('BG','europe'),
  ('BH','asia'),
  ('BI','africa'),
  ('BJ','africa'),
  ('BM','north_america'),
  ('BO','south_america'),
  ('BR','south_america'),
  ('BS','north_america'),
  ('BY','europe'),
  ('BZ','north_america'),
  ('CA','north_america'),
  ('CD','africa'),
  ('CF','africa'),
  ('CG','africa'),
  ('CH','europe'),
  ('CI','africa'),
  ('CL','south_america'),
  ('CM','africa'),
  ('CN','asia'),
  ('CO','south_america'),
  ('CR','north_america'),
  ('CU','north_america'),
  ('CV','africa'),
  ('CW','north_america'),
  ('CY','europe'),
  ('CZ','europe'),
  ('DE','europe'),
  ('DK','europe'),
  ('DM','north_america'),
  ('DO','north_america'),
  ('DZ','africa'),
  ('EC','south_america'),
  ('EE','europe'),
  ('EG','africa'),
  ('ES','europe'),
  ('FI','europe'),
  ('FO','europe'),
  ('FR','europe'),
  ('GA','africa'),
  ('GB','europe'),
  ('GB-ENG','europe'),
  ('GB-SCT','europe'),
  ('GB-WLS','europe'),
  ('GD','north_america'),
  ('GE','europe'),
  ('GH','africa'),
  ('GI','europe'),
  ('GM','africa'),
  ('GN','africa'),
  ('GP','north_america'),
  ('GQ','africa'),
  ('GR','europe'),
  ('GT','north_america'),
  ('GW','africa'),
  ('GY','south_america'),
  ('HK','asia'),
  ('HN','north_america'),
  ('HR','europe'),
  ('HT','north_america'),
  ('HU','europe'),
  ('ID','asia'),
  ('IE','europe'),
  ('IL','europe'),
  ('IN','asia'),
  ('IQ','asia'),
  ('IR','asia'),
  ('IS','europe'),
  ('IT','europe'),
  ('JM','north_america'),
  ('JO','asia'),
  ('JP','asia'),
  ('KE','africa'),
  ('KG','asia'),
  ('KH','asia'),
  ('KM','africa'),
  ('KN','north_america'),
  ('KP','asia'),
  ('KR','asia'),
  ('KW','asia'),
  ('KY','north_america'),
  ('KZ','europe'),
  ('LB','asia'),
  ('LC','north_america'),
  ('LI','europe'),
  ('LR','africa'),
  ('LT','europe'),
  ('LU','europe'),
  ('LV','europe'),
  ('LY','africa'),
  ('MA','africa'),
  ('MC','europe'),
  ('MD','europe'),
  ('ME','europe'),
  ('MG','africa'),
  ('MK','europe'),
  ('ML','africa'),
  ('MM','asia'),
  ('MN','asia'),
  ('MQ','north_america'),
  ('MR','africa'),
  ('MS','north_america'),
  ('MT','europe'),
  ('MU','africa'),
  ('MW','africa'),
  ('MX','north_america'),
  ('MY','asia'),
  ('MZ','africa'),
  ('NA','africa'),
  ('NE','africa'),
  ('NG','africa'),
  ('NI','north_america'),
  ('NL','europe'),
  ('NO','europe'),
  ('NP','asia'),
  ('OM','asia'),
  ('PA','north_america'),
  ('PE','south_america'),
  ('PH','asia'),
  ('PL','europe'),
  ('PR','north_america'),
  ('PS','asia'),
  ('PT','europe'),
  ('PY','south_america'),
  ('QA','asia'),
  ('RO','europe'),
  ('RS','europe'),
  ('RU','europe'),
  ('RW','africa'),
  ('SA','asia'),
  ('SD','africa'),
  ('SE','europe'),
  ('SG','asia'),
  ('SI','europe'),
  ('SK','europe'),
  ('SL','africa'),
  ('SM','europe'),
  ('SN','africa'),
  ('SO','africa'),
  ('SR','south_america'),
  ('SS','africa'),
  ('SV','north_america'),
  ('SY','asia'),
  ('SZ','africa'),
  ('TD','africa'),
  ('TG','africa'),
  ('TH','asia'),
  ('TJ','asia'),
  ('TM','asia'),
  ('TN','africa'),
  ('TR','europe'),
  ('TT','north_america'),
  ('TZ','africa'),
  ('UA','europe'),
  ('UG','africa'),
  ('US','north_america'),
  ('UY','south_america'),
  ('UZ','asia'),
  ('VE','south_america'),
  ('VN','asia'),
  ('XK','europe'),
  ('YE','asia'),
  ('ZA','africa'),
  ('ZM','africa'),
  ('ZW','africa')
on conflict (country) do update set continent = excluded.continent;
