-- =========================================================================
-- country_wiki_lang — какие языковые разделы Википедии читают в стране.
--
-- СГЕНЕРИРОВАНО docs/country_wiki_lang_build.py. Не править руками:
-- поправки, прочитанные глазами, живут в OVERRIDES того файла, вместе
-- с причиной каждой. Полное обоснование — в его шапке.
--
-- Источник: Викиданные P297 (alpha-2) → P37 (офиц. язык) → P424 (код
-- языка Викимедиа), отсеяно по живому sitematrix, плюс 13 поправки.
-- Строк: 384, стран: 251.
--
-- ⚠️ ШИРОКИЙ СПИСОК — ЭТО НЕ НЕБРЕЖНОСТЬ. Домашняя известность берётся
-- как МАКСИМУМ по языкам страны, и раздел, которого никто не читает,
-- максимума не даёт. Выбирает не список, а просмотры.
-- =========================================================================
create table if not exists public.country_wiki_lang (
  country_code text not null,
  lang         text not null,
  primary key (country_code, lang)
);

comment on table public.country_wiki_lang is
  'Страна карточки (alpha-2 или код подразделения, как в cards.country) '
  '-> языковые разделы Википедии, которые там читают. Генерируется '
  'docs/country_wiki_lang_build.py из Викиданных.';

-- Полная перезаливка одной транзакцией: карта — производная, и
-- «дописать поверх» оставило бы строки, которых у источника уже нет.
begin;
delete from public.country_wiki_lang;
insert into public.country_wiki_lang (country_code, lang) values
  ('AC', 'en'),
  ('AD', 'ca'),
  ('AE', 'ar'),
  ('AF', 'ar'),
  ('AF', 'ps'),
  ('AF', 'tk'),
  ('AF', 'uz'),
  ('AG', 'en'),
  ('AG', 'es'),
  ('AI', 'en'),
  ('AL', 'sq'),
  ('AM', 'hy'),
  ('AN', 'en'),
  ('AN', 'nl'),
  ('AN', 'pap'),
  ('AO', 'pt'),
  ('AR', 'es'),
  ('AS', 'en'),
  ('AS', 'sm'),
  ('AT', 'de'),
  ('AU', 'en'),
  ('AW', 'nl'),
  ('AW', 'pap'),
  ('AX', 'sv'),
  ('AZ', 'az'),
  ('BA', 'bs'),
  ('BA', 'hr'),
  ('BA', 'sr'),
  ('BB', 'en'),
  ('BD', 'bn'),
  ('BE', 'de'),
  ('BE', 'fr'),
  ('BE', 'nl'),
  ('BF', 'fr'),
  ('BF', 'mos'),
  ('BG', 'bg'),
  ('BH', 'ar'),
  ('BI', 'en'),
  ('BI', 'fr'),
  ('BI', 'rn'),
  ('BJ', 'fr'),
  ('BL', 'fr'),
  ('BM', 'en'),
  ('BN', 'ms'),
  ('BO', 'ay'),
  ('BO', 'es'),
  ('BO', 'gn'),
  ('BO', 'qu'),
  ('BQ', 'en'),
  ('BQ', 'nl'),
  ('BQ', 'pap'),
  ('BR', 'pt'),
  ('BS', 'en'),
  ('BT', 'dz'),
  ('BW', 'en'),
  ('BY', 'be'),
  ('BY', 'ru'),
  ('BZ', 'en'),
  ('CA', 'en'),
  ('CA', 'fr'),
  ('CC', 'en'),
  ('CD', 'fr'),
  ('CF', 'fr'),
  ('CF', 'sg'),
  ('CG', 'fr'),
  ('CH', 'de'),
  ('CH', 'fr'),
  ('CH', 'it'),
  ('CH', 'rm'),
  ('CI', 'fr'),
  ('CK', 'en'),
  ('CL', 'es'),
  ('CM', 'en'),
  ('CM', 'fr'),
  ('CN', 'zh'),
  ('CO', 'es'),
  ('CQ', 'en'),
  ('CQ', 'fr'),
  ('CR', 'es'),
  ('CU', 'es'),
  ('CV', 'pt'),
  ('CW', 'en'),
  ('CW', 'nl'),
  ('CW', 'pap'),
  ('CX', 'en'),
  ('CY', 'el'),
  ('CY', 'tr'),
  ('CZ', 'cs'),
  ('DD', 'de'),
  ('DE', 'de'),
  ('DJ', 'ar'),
  ('DJ', 'fr'),
  ('DK', 'da'),
  ('DM', 'en'),
  ('DO', 'es'),
  ('DZ', 'ar'),
  ('EC', 'es'),
  ('EE', 'et'),
  ('EG', 'ar'),
  ('EH', 'ar'),
  ('ER', 'ar'),
  ('ER', 'en'),
  ('ER', 'ti'),
  ('ES', 'es'),
  ('ET', 'am'),
  ('FI', 'fi'),
  ('FI', 'sv'),
  ('FJ', 'en'),
  ('FJ', 'fj'),
  ('FJ', 'hif'),
  ('FM', 'en'),
  ('FO', 'da'),
  ('FO', 'fo'),
  ('FR', 'fr'),
  ('GA', 'fr'),
  ('GB', 'en'),
  ('GB-ENG', 'en'),
  ('GB-SCT', 'en'),
  ('GB-SCT', 'gd'),
  ('GB-SCT', 'sco'),
  ('GB-WLS', 'cy'),
  ('GB-WLS', 'en'),
  ('GD', 'en'),
  ('GE', 'ka'),
  ('GF', 'fr'),
  ('GF', 'gcr'),
  ('GG', 'en'),
  ('GG', 'fr'),
  ('GH', 'en'),
  ('GL', 'kl'),
  ('GM', 'en'),
  ('GN', 'fr'),
  ('GQ', 'es'),
  ('GQ', 'fr'),
  ('GQ', 'pt'),
  ('GR', 'el'),
  ('GS', 'en'),
  ('GT', 'es'),
  ('GU', 'ch'),
  ('GU', 'en'),
  ('GW', 'pt'),
  ('GY', 'en'),
  ('HM', 'en'),
  ('HN', 'es'),
  ('HR', 'hr'),
  ('HT', 'fr'),
  ('HT', 'ht'),
  ('HU', 'hu'),
  ('ID', 'id'),
  ('IE', 'en'),
  ('IE', 'ga'),
  ('IL', 'he'),
  ('IM', 'en'),
  ('IM', 'gv'),
  ('IN', 'en'),
  ('IN', 'hi'),
  ('IO', 'en'),
  ('IQ', 'ar'),
  ('IQ', 'ku'),
  ('IR', 'fa'),
  ('IS', 'is'),
  ('IT', 'it'),
  ('JE', 'en'),
  ('JM', 'en'),
  ('JM', 'jam'),
  ('JO', 'ar'),
  ('JP', 'ja'),
  ('KE', 'en'),
  ('KE', 'sw'),
  ('KG', 'ky'),
  ('KH', 'km'),
  ('KI', 'en'),
  ('KM', 'ar'),
  ('KM', 'fr'),
  ('KN', 'en'),
  ('KP', 'ko'),
  ('KR', 'ko'),
  ('KW', 'ar'),
  ('KY', 'en'),
  ('KZ', 'kk'),
  ('KZ', 'ru'),
  ('LA', 'lo'),
  ('LB', 'ar'),
  ('LC', 'en'),
  ('LI', 'de'),
  ('LK', 'si'),
  ('LK', 'ta'),
  ('LR', 'en'),
  ('LS', 'en'),
  ('LS', 'st'),
  ('LT', 'lt'),
  ('LU', 'de'),
  ('LU', 'fr'),
  ('LU', 'lb'),
  ('LV', 'lv'),
  ('LY', 'ar'),
  ('MA', 'ar'),
  ('MA', 'zgh'),
  ('MC', 'fr'),
  ('MD', 'ro'),
  ('ME', 'bs'),
  ('ME', 'hr'),
  ('ME', 'sr'),
  ('MF', 'fr'),
  ('MG', 'fr'),
  ('MG', 'mg'),
  ('MH', 'en'),
  ('MH', 'mh'),
  ('MK', 'mk'),
  ('MK', 'sq'),
  ('ML', 'bm'),
  ('ML', 'ff'),
  ('ML', 'fr'),
  ('MM', 'my'),
  ('MN', 'mn'),
  ('MO', 'pt'),
  ('MO', 'yue'),
  ('MP', 'ch'),
  ('MP', 'en'),
  ('MR', 'ar'),
  ('MS', 'en'),
  ('MT', 'en'),
  ('MT', 'mt'),
  ('MU', 'en'),
  ('MU', 'fr'),
  ('MV', 'dv'),
  ('MW', 'en'),
  ('MW', 'ny'),
  ('MW', 'tum'),
  ('MX', 'es'),
  ('MX', 'nah'),
  ('MY', 'ms'),
  ('MZ', 'pt'),
  ('NA', 'en'),
  ('NC', 'fr'),
  ('NE', 'ha'),
  ('NF', 'en'),
  ('NG', 'en'),
  ('NI', 'es'),
  ('NL', 'nl'),
  ('NO', 'nn'),
  ('NO', 'no'),
  ('NP', 'ne'),
  ('NR', 'en'),
  ('NR', 'na'),
  ('NU', 'en'),
  ('NZ', 'en'),
  ('NZ', 'mi'),
  ('OM', 'ar'),
  ('PA', 'es'),
  ('PE', 'ay'),
  ('PE', 'es'),
  ('PE', 'qu'),
  ('PF', 'fr'),
  ('PG', 'en'),
  ('PG', 'ho'),
  ('PG', 'tpi'),
  ('PH', 'en'),
  ('PK', 'en'),
  ('PK', 'ur'),
  ('PL', 'pl'),
  ('PM', 'fr'),
  ('PN', 'en'),
  ('PN', 'pih'),
  ('PR', 'en'),
  ('PR', 'es'),
  ('PS', 'ar'),
  ('PT', 'pt'),
  ('PW', 'en'),
  ('PW', 'ja'),
  ('PY', 'es'),
  ('PY', 'gn'),
  ('QA', 'ar'),
  ('RE', 'fr'),
  ('RO', 'ro'),
  ('RS', 'sr'),
  ('RU', 'ru'),
  ('RW', 'en'),
  ('RW', 'fr'),
  ('RW', 'rw'),
  ('RW', 'sw'),
  ('SA', 'ar'),
  ('SB', 'en'),
  ('SC', 'en'),
  ('SC', 'fr'),
  ('SD', 'ar'),
  ('SD', 'en'),
  ('SE', 'sv'),
  ('SG', 'en'),
  ('SG', 'ms'),
  ('SG', 'ta'),
  ('SH', 'en'),
  ('SI', 'sl'),
  ('SJ', 'no'),
  ('SK', 'sk'),
  ('SL', 'en'),
  ('SM', 'it'),
  ('SN', 'fr'),
  ('SN', 'wo'),
  ('SO', 'ar'),
  ('SO', 'so'),
  ('SR', 'nl'),
  ('SS', 'en'),
  ('ST', 'pt'),
  ('SV', 'es'),
  ('SX', 'en'),
  ('SX', 'nl'),
  ('SY', 'ar'),
  ('SZ', 'en'),
  ('SZ', 'ss'),
  ('TC', 'en'),
  ('TD', 'ar'),
  ('TD', 'fr'),
  ('TF', 'fr'),
  ('TG', 'fr'),
  ('TH', 'th'),
  ('TJ', 'tg'),
  ('TK', 'en'),
  ('TL', 'pt'),
  ('TL', 'tet'),
  ('TM', 'tk'),
  ('TN', 'ar'),
  ('TO', 'en'),
  ('TO', 'to'),
  ('TR', 'tr'),
  ('TT', 'en'),
  ('TV', 'en'),
  ('TW', 'ami'),
  ('TW', 'pwn'),
  ('TW', 'szy'),
  ('TW', 'tay'),
  ('TW', 'trv'),
  ('TW', 'zh'),
  ('TZ', 'en'),
  ('TZ', 'sw'),
  ('UA', 'uk'),
  ('UG', 'en'),
  ('UG', 'sw'),
  ('UM', 'en'),
  ('US', 'ch'),
  ('US', 'en'),
  ('US', 'es'),
  ('US', 'haw'),
  ('US', 'sm'),
  ('UY', 'es'),
  ('UZ', 'uz'),
  ('VA', 'it'),
  ('VA', 'la'),
  ('VC', 'en'),
  ('VE', 'es'),
  ('VG', 'en'),
  ('VI', 'en'),
  ('VN', 'vi'),
  ('VU', 'bi'),
  ('VU', 'en'),
  ('VU', 'fr'),
  ('WF', 'fr'),
  ('WS', 'en'),
  ('WS', 'sm'),
  ('XK', 'sq'),
  ('XK', 'sr'),
  ('YE', 'ar'),
  ('YT', 'fr'),
  ('YU', 'sh'),
  ('ZA', 'af'),
  ('ZA', 'en'),
  ('ZA', 'nr'),
  ('ZA', 'nso'),
  ('ZA', 'ss'),
  ('ZA', 'st'),
  ('ZA', 'tn'),
  ('ZA', 'ts'),
  ('ZA', 've'),
  ('ZA', 'xh'),
  ('ZA', 'zu'),
  ('ZM', 'en'),
  ('ZW', 'en'),
  ('ZW', 'ny'),
  ('ZW', 'sn'),
  ('ZW', 'st'),
  ('ZW', 'tn'),
  ('ZW', 'ts'),
  ('ZW', 've'),
  ('ZW', 'xh');
commit;

-- Грант перечислен явно: политика без гранта роняла этот проект дважды.
alter table public.country_wiki_lang enable row level security;
drop policy if exists country_wiki_lang_read on public.country_wiki_lang;
create policy country_wiki_lang_read on public.country_wiki_lang
  for select to anon, authenticated, service_role using (true);
grant select on public.country_wiki_lang to anon, authenticated;
-- Конвейер эту карту ПЕРЕЗАЛИВАЕТ, поэтому ему мало select.
-- Грант на UPDATE забывали здесь уже дважды, и отказ был тихим:
-- «75 прочитано, 0 записано», оба числа правдоподобны.
grant select, insert, update, delete on public.country_wiki_lang
  to service_role;

NOTIFY pgrst, 'reload schema';
